#!/bin/bash
set -e
set +x

label=${1:-testing}

docker tag kaggle/rstats-build:latest gcr.io/kaggle-images/rstats:${label}
gcloud docker -- push gcr.io/kaggle-images/rstats:${label}

if [[ "$label" == "latest" ]]; then
	docker tag kaggle/rstats-build:latest kaggle/rstats:${label}
	docker push kaggle/rstats::${label}
fi
